plugins:
  - serverless-apigw-binary

custom:
  secrets: ${file(./config.json)}
  apigwBinary:
    types:
      - "multipart/form-data"

service: ${self:custom.secrets.service.name}

frameworkVersion: "3"

provider:
  name: ${self:custom.secrets.provider.name}
  runtime: ${self:custom.secrets.provider.runtime}
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  profile: botnorrea
  region: ${self:custom.secrets.provider.region}
  environment:
    BOT_NAME: ${self:custom.secrets.provider.environment.BOT_NAME}
    REDIS_HOST: ${self:custom.secrets.provider.environment.REDIS_HOST}
    REDIS_PORT: ${self:custom.secrets.provider.environment.REDIS_PORT}
    REDIS_PASSWORD: ${self:custom.secrets.provider.environment.REDIS_PASSWORD}
    FILESMANAGER_API: ${self:custom.secrets.provider.environment.FILESMANAGER_API}
    FILESMANAGER_API_KEY: ${self:custom.secrets.provider.environment.FILESMANAGER_API_KEY}
    ACTIVE_UPLOAD: ${self:custom.secrets.provider.environment.ACTIVE_UPLOAD}
    BOTNORREA_API: ${self:custom.secrets.provider.environment.BOTNORREA_API}
    TELEGRAM_TOKEN: ${self:custom.secrets.provider.environment.TELEGRAM_TOKEN}
    MONGO_USER: ${self:custom.secrets.provider.environment.MONGO_USER}
    MONGO_PASSWORD: ${self:custom.secrets.provider.environment.MONGO_PASSWORD}
    MONGO_DATABASE: ${self:custom.secrets.provider.environment.MONGO_DATABASE}
    MIX_PANEL_API: ${self:custom.secrets.provider.environment.MIX_PANEL_API}
    MIX_PANEL_USERNAME: ${self:custom.secrets.provider.environment.MIX_PANEL_USERNAME}
    MIX_PANEL_USERNAME_SECRET: ${self:custom.secrets.provider.environment.MIX_PANEL_USERNAME_SECRET}
    MIX_PANEL_PROJECT_ID: ${self:custom.secrets.provider.environment.MIX_PANEL_PROJECT_ID}
    MIX_PANEL_REPORTS: ${self:custom.secrets.provider.environment.MIX_PANEL_REPORTS}
    MAIN_CHAT: ${self:custom.secrets.provider.environment.MAIN_CHAT}

functions: ${self:custom.secrets.functions}
